pangolin_server_secret: ENC[AES256_GCM,data:k3CX2j+XGRPVXXXOXQUZGIAa4JzkJQF/hzwn7FNVGTDIvzLiwASSaV1GdSheRfm/rUlCkXAwOUmRXomsypUexg==,iv:VluJPtFROU50IEFJ24Bdu/0eF8NnuzDQmEFNoomOwK0=,tag:CNyoY25fLIb7FcOFNQ9izg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU240Yklndk9adW4yTmdn
            VWlGZStRUzNoaDhMQ3BqbWVwWjBWSnRwQ2hBCkZGVlpxU2dBU2hOVWlJakdjZG9k
            TTduOUtaTlNyUHI5MFpGbmNDTVRHOVEKLS0tIElNUGVxUkMzNHZMR2hmVnN6TnB6
            VDdrSXZ4bklUb1JOclJDTHJILzhrQnMK/ewlOpCRiJ8Eti8tINuxyy85Ze3O2Qa2
            UA5bKUZbdPOi416eSb2aEIQXug0/smGguwVDoRHZXiC6FltkP+kylQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-27T19:56:53Z"
    mac: ENC[AES256_GCM,data:0JZgJJvT/KOWFQoIrnV3jHrrO/m3nLilAga0s3/ZM/MkukbrZYYqfl5bQDj9cr5NwIbLL7U68VVeG0xWPrKefdsRdFYszenZS6Z4ncyWyTeEzuxb5U9an88IiURa+WoW2jN2lKMTh1QIaqtwKGtg7b48UehshxZYicTdb4yoVPk=,iv:UZgnPUO+ZduRid7ZwUltQYB9q0v07iVBlQNjkOCiVRE=,tag:H/+5AiSdavJjt2/Fp/Bttw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
