pangolin_server_secret: ENC[AES256_GCM,data:k3CX2j+XGRPVXXXOXQUZGIAa4JzkJQF/hzwn7FNVGTDIvzLiwASSaV1GdSheRfm/rUlCkXAwOUmRXomsypUexg==,iv:VluJPtFROU50IEFJ24Bdu/0eF8NnuzDQmEFNoomOwK0=,tag:CNyoY25fLIb7FcOFNQ9izg==,type:str]
headplane_cookie_secret: ENC[AES256_GCM,data:YQG5QYUVVIurjCAWAJ/uWbesoTOPxtYy9nkHtksRqvQ=,iv:HSIISNIu3UPEZl+3G73blcGxKNBrnYo9hcqHl7ehzO0=,tag:Orjg5UN9Bx2pk/I+wQn1FQ==,type:str]
pangolin_blueprint_api_key: ENC[AES256_GCM,data:1eWq5M0MWBxlYTnh6Mv9w73A3bRjIqb2abJohBxSjHHL+8Whnbh5kmQeLAiS3jJPpk7q1Pz7JtQ=,iv:zGimSFCcU8a9K0g1fBubM64GFswjL8klBzjRz7cyZao=,tag:XA0035TSLp/0Uy2DjEiohA==,type:str]
pocket_id_encryption_key: ENC[AES256_GCM,data:YJuGTYovO7Yv+qzC+inSwP4pQnB7R0AnXxI6DVSiQT1pdM68XQNgBjz7u8A=,iv:+SjK/cYExummLGP1K3Mw1YGuXema9DK+YkTl1MPnPqM=,tag:MsSYrorKiwTysIBfmDjTCw==,type:str]
vpn_oidc_client_id: ENC[AES256_GCM,data:JuifKPjH3UpraG1NRgB0Bkr6vAIbDiKaws3yWuwo4Wd7Z7WW,iv:R8g85yrGrHsP5dAGuLQY/khMZXlGUYEg39hiLZ6/QSA=,tag:hOGhg/Yakz88cpzFhT9OQg==,type:str]
vpn_oidc_client_secret: ENC[AES256_GCM,data:e7lK06AlRqLf2bO+5nRXHJtLR9mk7nad8NZudsZ29Yg=,iv:NrvdlnEn7H4cyRo6zXUR92KmDpx0KTSm6TZ/tHVPfbA=,tag:nzHmb2kwVJ0I0e9BQtrGSw==,type:str]
backup_restic_password: ENC[AES256_GCM,data:z0s6Ngrxzuyx312zBHZP47+5S3RX/uV7tA/6f2nCL4WOqLs5zC8J5aid62uW8hOq,iv:/rbNAKBjxvNipdqYvmJfH+BJHn4zoY8YRQMIGa6CSvc=,tag:bDoohAyk7KA2haTbvPE9kA==,type:str]
backup_r2_endpoint: ENC[AES256_GCM,data:mQusOeYiVz8UIFARJ3kTScR727wtFHG6KuObayFoeLMikjh5yegH58xDyZDrGGrAi6ZVTSme0Dp2RLhWDArSJOQ=,iv:0XV8RQRMStkYl8OhG4/XNkaYm92a0pNPSuBW0TaeFME=,tag:5XmRrHYCj46X/bsOeFM99Q==,type:str]
backup_r2_access_key_id: ENC[AES256_GCM,data:H7lp0WIB4cyOXmX5A24G9BXZOhAM0jNwhGokZJBFL0c=,iv:3o676lFPyUcF2NjMGiZpJf7fh8IUXmixcTff9btsG7w=,tag:fydMHBjI2KpK1tSh+uDh5g==,type:str]
backup_r2_secret_access_key: ENC[AES256_GCM,data:ycaSnTvqA8GAYQLEDJ5RVW7OWaMnNIePPaCM1xpfOe4BMDMQURLvx4hLg2ImlDbAnnQx/8XSsRUU/iJT7VDfgw==,iv:ffnkM15/yHfyDTJSKymmuM05Zm744Q0DXn7GZE+0Zxs=,tag:AzisZc9FDQT8JoM54rLEcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU240Yklndk9adW4yTmdn
            VWlGZStRUzNoaDhMQ3BqbWVwWjBWSnRwQ2hBCkZGVlpxU2dBU2hOVWlJakdjZG9k
            TTduOUtaTlNyUHI5MFpGbmNDTVRHOVEKLS0tIElNUGVxUkMzNHZMR2hmVnN6TnB6
            VDdrSXZ4bklUb1JOclJDTHJILzhrQnMK/ewlOpCRiJ8Eti8tINuxyy85Ze3O2Qa2
            UA5bKUZbdPOi416eSb2aEIQXug0/smGguwVDoRHZXiC6FltkP+kylQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-28T02:11:32Z"
    mac: ENC[AES256_GCM,data:xkBrhWY6nq434DifPCaR5oIHqnZxg5pc095HyXoqG5z282Tx6N8EUnblRMCUjpJeEak/58VZgFj3X2hL69X8Dff7iBIFhA1DgbeymkTvfFtfDxPyWu9Ml+Xwj07eUlWu9CErlhlntDUDKUgEIiSA93H+2qYM5pfBIaWoS7MFUX0=,iv:srqNpMNYlah/4cMLMobwMvzZX1wLE86wKytKSucw/Vo=,tag:T+ok3lpUo6jOPkTSjMyN5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
