pangolin_server_secret: ENC[AES256_GCM,data:k3CX2j+XGRPVXXXOXQUZGIAa4JzkJQF/hzwn7FNVGTDIvzLiwASSaV1GdSheRfm/rUlCkXAwOUmRXomsypUexg==,iv:VluJPtFROU50IEFJ24Bdu/0eF8NnuzDQmEFNoomOwK0=,tag:CNyoY25fLIb7FcOFNQ9izg==,type:str]
headplane_cookie_secret: ENC[AES256_GCM,data:YQG5QYUVVIurjCAWAJ/uWbesoTOPxtYy9nkHtksRqvQ=,iv:HSIISNIu3UPEZl+3G73blcGxKNBrnYo9hcqHl7ehzO0=,tag:Orjg5UN9Bx2pk/I+wQn1FQ==,type:str]
pangolin_blueprint_api_key: ENC[AES256_GCM,data:1eWq5M0MWBxlYTnh6Mv9w73A3bRjIqb2abJohBxSjHHL+8Whnbh5kmQeLAiS3jJPpk7q1Pz7JtQ=,iv:zGimSFCcU8a9K0g1fBubM64GFswjL8klBzjRz7cyZao=,tag:XA0035TSLp/0Uy2DjEiohA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU240Yklndk9adW4yTmdn
            VWlGZStRUzNoaDhMQ3BqbWVwWjBWSnRwQ2hBCkZGVlpxU2dBU2hOVWlJakdjZG9k
            TTduOUtaTlNyUHI5MFpGbmNDTVRHOVEKLS0tIElNUGVxUkMzNHZMR2hmVnN6TnB6
            VDdrSXZ4bklUb1JOclJDTHJILzhrQnMK/ewlOpCRiJ8Eti8tINuxyy85Ze3O2Qa2
            UA5bKUZbdPOi416eSb2aEIQXug0/smGguwVDoRHZXiC6FltkP+kylQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-27T21:54:41Z"
    mac: ENC[AES256_GCM,data:EWhOOiKhvy1a57XuBeH5i3REC0Dz6XwltTqhDo19Ve8bKFXIRI9un7hvMuzSaIhKBJ2LyqAom3/GIsvkcHQxGwOOq5yZxI8bU4i80tMEz2HpW7cYKNSktJZpx0i2aVEH6Fd3NuNFK5iW0p17K/V+epPj0/nKX2i1aS2N0O64yIE=,iv:59ixDMjP+cbaYOv3fiKEeV4A6yTbkt2GtSaFH3RezAM=,tag:bjaQEAIqoaZ/g3ynZ7Q53w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
