apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: termix
resources:
  - namespace.yaml
  - tailscale.sops.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
configMapGenerator:
  - name: termix-opkssh
    files:
      - config.yml=opkssh-config.yml
