apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: filebrowser
resources:
  - namespace.yaml
  - oidc.sops.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
configMapGenerator:
  - name: filebrowser-config
    files:
      - config.yaml
