apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multica
resources:
  - namespace.yaml
  - multica.sops.yaml
  - storage.yaml
  - backend.yaml
  - web.yaml
  - httproute.yaml
