---
docker_apt_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  ppc64le: ppc64el
  s390x: s390x

docker_packages:
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
