---
all:
  children:
    proxmox_nodes:
      hosts:
        atlas:
        gaia:
        hyperion:
        tartarus:
        theia:
    service_hosts:
      hosts:
        hermes:
          ansible_host: 192.255.220.7
          ansible_user: caleb
          ansible_port: 22
