---
all:
  children:
    proxmox_nodes:
      hosts:
        atlas:
          ansible_host: 10.0.1.124
        gaia:
          ansible_host: 10.0.1.120
        hyperion:
          ansible_host: 10.0.1.101
        tartarus:
          ansible_host: 10.0.1.113
        theia:
          ansible_host: 10.0.1.131
    service_hosts:
      hosts:
        hermes:
          ansible_host: 192.255.220.7
          ansible_port: 22
