admin_user_password_hash: ENC[AES256_GCM,data:ir41cETLvelXtOE9U5jlhieq4rRUrgpr9zjXVM1CGX8Hg1q8g7COCQKuRIl+FKRl7Ze/QrFdAsumy17dTU3vm1gYnv+XNKsmlqvFiqMdCTWdxyjgtyQeP3grWSC6rriF4b7jg5oVeJXJ2g==,iv:/sbPcmsWcZFd81B04cNaLZeY6Lmymouj5TekersEf5M=,tag:K3fqIsyXx0hx0E19sQrkBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYU1XcktJVkkxNldmWi91
            eTlPK01MZEdtRmpIV2g2eDhLT29RbmlKWGprCnNuRGpnNEIwcDB2bTNvQUhaUlgr
            Q1NmY2pudk9rS0tnTzJSM1JHMVpnZEUKLS0tIC9sL0hncDB5cmdjbEo1dk5aMitv
            N1ZGQWFOTWMrZHZJOTZCdm1wZjcyd2cKGA3wF2IXWktVxUdV9zApzk+pLWG667V9
            531jrhZ9vKstJRBqvQwSy5Gt1kG/moBg6t4dhW4vEeRibB+lpHo09w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-27T20:59:12Z"
    mac: ENC[AES256_GCM,data:PqqZ0gEYP4/yswdseys0f0zH28s4lspcjQ06lGv1Lre5li/hB43ON2UysPIsszi6xL2Bit/VFLaOSTgnvfQNRrXlk57Hf3tTEz8JEAT9Bf3aLI6Prjl9jz/MNpm7GE0svGYl7+m3XRfB8JFaepqIS8JozWo890DnEaz6boRiPYo=,iv:d6vm4O7iMkZ6NuWdnEV39mVs8sM9KmZJhVde830PZec=,tag:NsxqYKghKW0lkLayMbU+/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
