proxmox_cloudflare_dns_token: ENC[AES256_GCM,data:RNSX247I3mGtZIbgv19eUpQd1ihJQVdF66giQvKhHkisHWQfg5eVAsRidxGDl9sQsQwLl04=,iv:zYE04eWVb0AdJIuGn8s7C57QralV4/r51DvBBefQQoM=,tag:RrqOnsFyBtjQEAuWVh9eEQ==,type:str]
proxmox_oidc_client_id: ENC[AES256_GCM,data:FN/0Kz8/KMjQqSl3qwoQhLVa33RlC+HvAJTMHE1PIqYLxz/N,iv:o6vIyO6yMACxonCAojIni+p3eiJ5x62eEQwJs6oMe4g=,tag:9KOd9fz328auUjXbeQKjvQ==,type:str]
proxmox_oidc_client_secret: ENC[AES256_GCM,data:9HEjf3EGO+zLdk2wIrOMeW6/m+hiUYBgwcRHjHEYszM=,iv:dt2z6pQld8eLTpJy2wCsmlP8+RjJ23n/khFmEwNDbts=,tag:hNscNl3i5/kb3VVbIHbd5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTmMway9zQzRLaFUxUElx
            a0tJUkJmSWVFZ0hUVGliNXNtRERpZFVDSWxnCjVqQmwrVjZneXozV0pTUkZWbm1J
            aGQ3NEdzMnZwVGxUZk5teVN1VkRKYXcKLS0tIFZUZUowdlZkb2ZMMlFUcFdBSEE0
            Mm93cFhxdUkrVEtoVEQvSlBsTGh5eEkKQS+g2aJHfrBfXlOVALH8rylVDDAjq7Zu
            1AHK7kHi0bpvd9zsR4IZAO/SMaWAlYM83/jTy9wEhtQazv+iGUv1hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-28T02:42:52Z"
    mac: ENC[AES256_GCM,data:uph1c7EtGIpQ8/sbKt9qCKlIxfdyM+vU61bGoqToJSzM1pwRDwng5/JqjdCfvYKLFfH5A0GPbR13SIivMbdTw9VjmgAAHXmWuOxqLdX2ZuRWcXLVZuaImFs8QlqCJkopB8AwsMB6067u9ZsMPZ+Vvr3LvBdefhX1wSqAcNzxOTc=,iv:DdT4A5ahFfrdNePJbfXbL3+wlYQg0Rc0Hf4H+r4EAMQ=,tag:YEdVtJ1QpJywPFCkICxlmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
