---
- name: Configure Proxmox hosts
  hosts: proxmox_nodes
  roles:
    - role: common
    - role: admin_user
      tags: [admin_user]
    - role: ssh_hardening
      tags: [security]
    - role: sysctl_hardening
      tags: [security]
    - role: unattended_upgrades
      tags: [security]
    - role: tailscale
      tags: [tailscale]
    - role: proxmox_web
      tags: [proxmox_web]
