#ENC[AES256_GCM,data:uNBWU+9vDwixA+mp9FWE6ADtUO2OaJU7LP+rqjKIQhZloOkfwVfu9TdqFrMbxSrbm2IaIv3kT+z9+tw=,iv:qTt1Xw9xOJijZSV+QI6rVL69g4QKhsm2Crd2Y0LYSBE=,tag:XRBTTJ4ftqwGU0Jeq7b+5A==,type:comment]
samba_user_passwords:
    caleb: ENC[AES256_GCM,data:LvdzHln9n4KcvKd1,iv:3+/dMqySF80LyVhnBk6mYEuQik8Yh3wOytm9DYRAa+c=,tag:38jRjqw2fkgwxYkNMuENyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bEIxOTZhUFRRYkgrdVlq
            V3d1ZnA3UEF1RFFhUkJ4NnBjRUpnampmdWwwCjRRdjhHT3g5dVgxc2xIZzlNdFhP
            ZDhvMUtNSTR3dDJEcVhhSFlWNnY4K2MKLS0tIHY0V0Y4TDBjakRyM2JaRkFHb29F
            d3Z5K1oyU3g0c0FtbmhTamtUVGZ6TGMKGtIj8pGw+T31SEBsCL0bUQup9ri3XpSz
            cvl5BiZnj679kBKqypC7evS2OE1AV8Mnsra1op5PpNuRjjvBX6npNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-10-07T01:53:41Z"
    mac: ENC[AES256_GCM,data:91ckU49xiS/3cQOzil5/rYr7Wng5UDJBOpJpsHqwtTRm/D1+icI45nap7FHtrvgtgs9FRCTCmOV0I6EH5zNoqb5jHRlZLcuUeUmOu+8ZQTikkeXhjJ/cuckLAaphG2m2gXQpqugGArdgbtFznp4J6gRxcXLYVuAJ7R8AFdRou7o=,iv:FNHsybW8P2SPtlKHfYo/mi4eM+ujHCXfe8JfCbvdQf4=,tag:ZLBKQOEGokJ+N6qCMwQ2cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
