# The secrets of Kaneo. AUTH_SECRET is random. Set the password of
# PlanetScale in DATABASE_URL, and the Pocket ID client, with sops set. The
# callback URL of the client is
# https://kaneo.buildwithcaleb.com/api/auth/oauth2/callback/custom.
apiVersion: v1
kind: Secret
metadata:
    name: kaneo
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:2wEjOHDXF6AWDBjuOBxaV95uwbRlDhU1q9Pq+401k6Uc+A1WdvVHD5FK/aP1JWeX4cCo629SJRDzIRDFzsejekFq9gdfbxkwBgQi9CzjQZfYnuW3x8A1USJHbJFjhJfhVp8/Hcrp89C8RLEdy+dyCcRtQuxEmQQoCRjIJpw7AvIoTRl4,iv:nAmlpnLAD21l3blUMro7+ufCJ19E8WPfQebH6Axiu1g=,tag:lM/BJ8cG+OtLP7em/+80hg==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:F/yUOOmwws1jBJ0LMXZqrMmWeBjoKKNn8nERcZiBCPAuY/W/3Ny8r0+yqge95Z2BoG1koKMyhuCGUM8S3aUs2A==,iv:f2xSRblWgs4WnjKBNihZrtCfLoiu2tRVOEfirob/8yY=,tag:g6sWCw7+C5S6At4eRngIxg==,type:str]
    CUSTOM_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:QNpx3mN4QoK8mXnnhFC8Rrw4pta71V0QtT2tssqDw46rbdUu,iv:8zrZAE8K1/4o80Qf/BJiR+oJ30bqW7l/kdJH2ZdIWg8=,tag:mty1lqpDjvRqRViFa2snwg==,type:str]
    CUSTOM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VQEfbLOiQ7L19R/Z0+qCqRQuMDx5j3Y2q2NqCBY0k3s=,iv:+TOD9UXCLElGFEYqmeYACo7k0t0sCCIUKKteXCUQJJY=,tag:7BQMS/xkh0BfzTIVwob1Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2lKWEdacHlHb3Nxb0Iz
            MnFDZ1kyT1FIdjdmMFpOT0hJWU10ZmRrSkV3CjJ2R0VDRkE2TVNlZ0xJZC9TSFJG
            ZnRZYWVFdlBDOUxLcTcxN0ViMmhtdTgKLS0tIDd4ZHc5czJHdWNBeXFoZkFVUEhZ
            ZGNrbU9mb0RlRVlrYzBlYzR3VXRWTlkKpeghNovRbjmZhjD19SAHEqtexRYv5CDI
            34HUodr9GImtkRR8MfssNS9GxZiUuvkHP84RbRm35GYYo+p2TLjJnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzlXTm83MFBRdmVBa3RX
            U2pnYmE5YWMzTnlQZnh3ekJjMy9ybkhPWG5FCjdQRjlLSnVLWHhBSEt6bkpNU2l4
            NGhuMjM5ak1jMmcvWXMxNjhOTjVvQUEKLS0tIEFjajhWMXB3aUFuWDIrK3NEOWI5
            WnJZeVhzb0ZZVWRkKzNyem1tQytVUmcKoI5M1yBpKLe11IMHuwpwAae7LvFUZV8p
            /1mOHUmRc3HVDIVKgxH4J/FL3r9Y8SreS8MNaTM9P8mQQ9fkXKE7xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzl2a35end05nnw7ajecjyk3zz46azqjnhq09h63k9yjhznua3yqvqmcwk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T04:25:35Z"
    mac: ENC[AES256_GCM,data:tr/gNwABGsxchdnszGbf+XiwasSASwoOxuzWqEnQUqjcTeG9wYpM4ynIc13XcQYsdPGGS5wV2lwDKU78fMPZL5NAEA1UEF6iKDXE1PYm4XDfk4w7El3WTTsAW2uLt7z+XizcszCN4VxtSz0QeBek3tCOHq1jQz7Z/1kurMGim7Q=,iv:ekdoCQqZhj4TODdWlG4Z9KO4AnFWFwdZsZ71TntQcqQ=,tag:a7oui1GVwcJwqhkEJMJxdw==,type:str]
    version: 3.13.3
