admin_user_password_hash: ENC[AES256_GCM,data:HPB4bFwDfjC4/xSUEDSNb0qcL3IiyyaUIzZ2UxcD79MDjTs8hUDi8y2ICuayKyb1rUdiDwwJ7hseK4SlQR+7nGJMbvY5NHtBF1/vNba4+OnKzmetHf45WtJ9sWFeCOMggpV//EqTt88A3A==,iv:rvV5fdkAJd+7TcP447TscDNj9Byw+OE8AFCoUXDcFfU=,tag:MwPTAyfJ2oaRUU/QxbLv3g==,type:str]
ansible_become_password: ENC[AES256_GCM,data:IOs4B4jO8zLvWaW4,iv:VZ1umthU9boYJ+DXpDsXmZGL/c5d+yeuysS3x7UCMXg=,tag:05w1jb+/N/5c69VYr9A38w==,type:str]
owner_user_password_hash: ENC[AES256_GCM,data:fdd1KXvEy3SGQA8Klt/qE53msZCl9uZh/imEAZwNJbZ3dBK6c07sic6ooL1qSwJYxkBYNzdRJCINrC2WMaA8Kx780UcYPI/wZabKynSHEyrgHZ4BbMImvfDZCRvrInd2CMe3aBEdl5C5Ww==,iv:8b5iV6+zqp5UXhBPFQCjcgrTJrJs9jW+JpWoQ1nllso=,tag:60wMaOfe1ZghBGT9XcbwBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSDNXWnhXWW5XdnF0dXM4
            TnkyQW1ZSlplSFIzK0FTY1lyYkM5NnV3OHh3ClMyQ2tWQVFiSDlDNFlOenlCdGln
            NmpnVlhSL0pUNFpIWEw4YXNwT3g3ZWcKLS0tIEUwMGVBT1gzNG5nMlVwVDBjMnNi
            NnJjL0dZcXZuc3JZYlNqSlJZak9IZDQKfcaYE/5OA3unVtqx92N6CFwexU/+RWdc
            QI2T6cz8KEogqztRqgA+dOn7su7PvncT1m646UPpvg+4Ngtu9ICU+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-10-10T22:12:36Z"
    mac: ENC[AES256_GCM,data:jnr94rFvQegc5Ey5Sw1E1CdNGZq3762I56j6SgJbklG61L9VNq+iXZJJ4rbWb+d9IiihC212CDXmNxPOAFsnrMZTUniNJKKF+sM+xXQGEd3C75z5tpjXkRJvJkopUtwwU9Q1VDHgilJBVWIt5o+im3ntC2Rmv1O2sdtbhdCv6tY=,iv:plEMuGSpZaIKb+ZOpw9CBW67jJEU9ncZAUspUAGoWgM=,tag:ZRGRT4Zl0BUkNI7pDzUjog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
