admin_user_password_hash: ENC[AES256_GCM,data:HPB4bFwDfjC4/xSUEDSNb0qcL3IiyyaUIzZ2UxcD79MDjTs8hUDi8y2ICuayKyb1rUdiDwwJ7hseK4SlQR+7nGJMbvY5NHtBF1/vNba4+OnKzmetHf45WtJ9sWFeCOMggpV//EqTt88A3A==,iv:rvV5fdkAJd+7TcP447TscDNj9Byw+OE8AFCoUXDcFfU=,tag:MwPTAyfJ2oaRUU/QxbLv3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSDNXWnhXWW5XdnF0dXM4
            TnkyQW1ZSlplSFIzK0FTY1lyYkM5NnV3OHh3ClMyQ2tWQVFiSDlDNFlOenlCdGln
            NmpnVlhSL0pUNFpIWEw4YXNwT3g3ZWcKLS0tIEUwMGVBT1gzNG5nMlVwVDBjMnNi
            NnJjL0dZcXZuc3JZYlNqSlJZak9IZDQKfcaYE/5OA3unVtqx92N6CFwexU/+RWdc
            QI2T6cz8KEogqztRqgA+dOn7su7PvncT1m646UPpvg+4Ngtu9ICU+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-09-27T23:52:12Z"
    mac: ENC[AES256_GCM,data:gVCj16SPnSuyHphp/GOKhIJDJY8OQgyderuFY3XPPquRXujDq9TznW8xYaIlc6NTHKQ7TRMKXsn2yoEuCKYGXJB0hw3PZ16Inlab98hov8fH4EHLUNQZ2ZzV0u+RGI/6Zuvp+4kIpxs4M47MVpEtmJT/hdLkojpBWStGJU0yRdc=,iv:+MmO8fIoBFFQ6WzrgjiV1SJOaw/xxKO3Lu5/JJH4Itw=,tag:iUGhlp8CdPsDHDcJ+GoBVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
