admin_user_password_hash: ENC[AES256_GCM,data:HPB4bFwDfjC4/xSUEDSNb0qcL3IiyyaUIzZ2UxcD79MDjTs8hUDi8y2ICuayKyb1rUdiDwwJ7hseK4SlQR+7nGJMbvY5NHtBF1/vNba4+OnKzmetHf45WtJ9sWFeCOMggpV//EqTt88A3A==,iv:rvV5fdkAJd+7TcP447TscDNj9Byw+OE8AFCoUXDcFfU=,tag:MwPTAyfJ2oaRUU/QxbLv3g==,type:str]
ansible_become_password: ENC[AES256_GCM,data:IOs4B4jO8zLvWaW4,iv:VZ1umthU9boYJ+DXpDsXmZGL/c5d+yeuysS3x7UCMXg=,tag:05w1jb+/N/5c69VYr9A38w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSDNXWnhXWW5XdnF0dXM4
            TnkyQW1ZSlplSFIzK0FTY1lyYkM5NnV3OHh3ClMyQ2tWQVFiSDlDNFlOenlCdGln
            NmpnVlhSL0pUNFpIWEw4YXNwT3g3ZWcKLS0tIEUwMGVBT1gzNG5nMlVwVDBjMnNi
            NnJjL0dZcXZuc3JZYlNqSlJZak9IZDQKfcaYE/5OA3unVtqx92N6CFwexU/+RWdc
            QI2T6cz8KEogqztRqgA+dOn7su7PvncT1m646UPpvg+4Ngtu9ICU+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
    lastmodified: "2026-10-08T02:23:13Z"
    mac: ENC[AES256_GCM,data:PVdHBQnuDuIEfFzwq8cN+K3VpNRFwcQAdSEaMxjBWBX37vwkhFDCIWTtldwjxtM3toXt2E3t76jUQUMT+xND51Q4OZVnTMc1ireh7RdT9zFP1PdhQ4/KvGAlzB6Ku/x8FnDwMwDe4NsXsf/d0uR7cAia8dfoILrTBqOwR6uX47g=,iv:GfczAHuZrXC2HbuZ0pTCbaaxXY49BxihctwNulhn+EQ=,tag:F06AMOeRo/foYnUalbdkhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
