apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helmrepository.yaml
  - web-config.sops.yaml
  - helmrelease.yaml
  - ciliumnetworkpolicy.yaml
  - rbac.yaml
