# The API tokens of Proxmox for Glance. Each token is for the user glance@pve,
# with the role PVEAuditor, so it can only read.
apiVersion: v1
kind: Secret
metadata:
    name: glance-secrets
type: Opaque
stringData:
    proxmox-pantheon-token: ENC[AES256_GCM,data:NuV+36h7+JaBoEQ+dp3tFEnisEN7/qojcUw/UaSb4a0tosQ8,iv:hz/WzXPjtTU7FBUJzhCrRg0OcywlcGe9LzPLadNnZso=,tag:jdFyfZe+3hJnAd0IUDd9JQ==,type:str]
    proxmox-atlas-token: ENC[AES256_GCM,data:4dqhIK1D70/I50CW1B6U773yW2u1p41xUc6EQFRWAwaeCimH,iv:pDuHk6ae02YCJeYClQnjfrnCfWeT1li4Df5Qxq24aqM=,tag:99PWvPH7og5V7ryQHgEhSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T2NYVWo3WkZqTWZhV1JY
            Y1lIS1NseTJwd0hJdE9ybDdIK21rQWw4NndjCk0zeGZpVHNpc0JjU1RsS1ZNSTNQ
            dm1ONXBLRmprRG9jYjNrZ2lyek4wQUEKLS0tIDZXY29rcHJITHNZTHkzWDkzb29T
            djV5aVY5QkNQdGZ2MDJwdmI1c0JXUzQKPUBImvvqqMzQafBh0I6eY0MoszwgX3j0
            B8qLzdTzbByVVWnPDXrV3TT11KDe7HlaCSqpU+a0YNkSXcjcYCPKYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7cjpt7nmnm89sn5e6evshkkc6zacga8eazkce5eww789clw9jq5tlp4d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaVZ3b0hzajFXK3U5dkpT
            SVF3NTdYV2pMQW04NGt5V2N0ZHk2NmJRSGkwClNCWEdHQ1d1NFNFOGxobGV1b1hx
            d1FyRGJSU1NHLzhEVFVqcHB0Q3JnME0KLS0tIHU1TVBIWHJmMXdWUXc0MFBkWnBo
            UlMxUE1QZ01vVzM5N01XaHlIM05rQXMKk8fjzrFrIVfUspvUSxvoSBieD4ci/XDv
            BVQfm4h/iVamZCEis7fdo5PCtdseNqEcvl2I2ULtG2n0IB1dgghTYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzl2a35end05nnw7ajecjyk3zz46azqjnhq09h63k9yjhznua3yqvqmcwk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:56:35Z"
    mac: ENC[AES256_GCM,data:ga4j9iSdoUHkvmHmA190L0rHXv+HoLfGmvGCxMT1Uir80erL5vQcZDJuGpT+cKbKgU3zolH6aOTGGBHtsrTEXsj+TPVs72mIFVVFvdAZFmPUVq2JXorQ+e5rzJAn8/Yy6q6wq4r0i2hCoDT+qRsQJqHLkGpHY+0qk/W0jXD+Pxc=,iv:zrbpMji+y1zow1vHvu3fGxp9m7K0lBqWXBSOilNbBSM=,tag:7UtTE9ZWJmu2R9gCCbZFOg==,type:str]
    version: 3.13.3
